spring:
    application:
      name: spring security
    datasource:
        username: sa
        password: password
        url: jdbc:h2:mem:my-db
        driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console.enabled: true

